$file = "c:\projects\pdf2csv\pdf-to-csv\server\src\services\documentProcessor.js"
$content = Get-Content $file
$newContent = $content[0..830] + @(
"        // Deduplication Logic:",
"        // 1. Group by mobile number",
"        const mobileGroups = new Map();",
"        const records = filteredRecordsRaw || [];",
"        ",
"        for (const record of records) {",
"          if (!record.mobile) continue; // Should be filtered already, but safety check",
"          if (!mobileGroups.has(record.mobile)) {",
"            mobileGroups.set(record.mobile, []);",
"          }",
"          mobileGroups.get(record.mobile).push(record);",
"        }",
"",
"        const uniqueRecords = [];",
"        const duplicateRejected = [];",
"",
"        // Helper to count populated fields",
"        const countPopulatedFields = (r) => {",
"          let count = 0;",
"          if (r.first_name) count++;",
"          if (r.last_name) count++;",
"          if (r.dateofbirth) count++;",
"          if (r.address) count++;",
"          if (r.email) count++;",
"          if (r.landline) count++;",
"          if (r.lastseen) count++;",
"          return count;",
"        };",
"",
"        for (const [mobile, group] of mobileGroups) {",
"          if (group.length === 1) {",
"            uniqueRecords.push(group[0]);",
"          } else {",
"            // Find best record",
"            // Priority 1: Has Address",
"            const withAddress = group.filter(r => r.address && r.address.length > 5);",
"            ",
"            let candidates = withAddress.length > 0 ? withAddress : group;",
"            ",
"            // Priority 2: Most populated fields",
"            candidates.sort((a, b) => countPopulatedFields(b) - countPopulatedFields(a));",
"            ",
"            const winner = candidates[0];",
"            uniqueRecords.push(winner);",
"",
"            // Mark others as duplicates",
"            for (const record of group) {",
"              if (record !== winner) {",
"                duplicateRejected.push({",
"                  ...record,",
"                  rejection_reason: 'Duplicate mobile number'",
"                });",
"              }",
"            }",
"          }",
"        }"
) + $content[845..($content.Length-1)]
$newContent | Set-Content $file
